include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: false
